---
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 7

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "17"
      tests_patterns:
        - src/test/**
