---
name: Reporting

on:
  workflow_run:
    types: [ completed ]
    workflows: [ BDD ]

permissions:
  contents: write

jobs:
  report:
    name: Publish test reports
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download CI reports
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          branch: main
          name: surefire-jacoco-reports
          path: target/site
          workflow: ci.yml
      - name: Download BDD test reports
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          branch: main
          name: serenity-reports
          path: target/site/serenity
          workflow: bdd.yml
      - name: Add top-level test reporting page
        run: |
          cp .github/pages/index.html target/site/index.html
      - name: Publish test reports
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: target/site
